### ISSUE TITLE
pip装不上 求指导~~

### ISSUE THREAD

**Issue by daliali2088** [SWHL/RapidVideOCR#11]
![image](https://user-images.githubusercontent.com/77323405/156006036-c2c70fa0-8197-46d1-bd4a-40c336e6d6c0.png)

![image](https://user-images.githubusercontent.com/77323405/156006562-9e3b214e-eaf2-4a0e-bf8e-66c4a0bb6e71.png)

**Comment by SWHL** [comment]
- 你的终端环境是什么操作系统？
- 可以尝试直接安装：
```shell
pip install onnxruntime -i https://pypi.douban.com/simple/
pip install decord -i https://pypi.douban.com/simple/
```

**Comment by daliali2088** [comment]
> ```shell
> pip install onnxruntime -i https://pypi.douban.com/simple/
> ```

谢谢 我今天重新装了个py版本正常了

**Comment by daliali2088** [comment]
我又遇到一个新的问题 是不是我哪里操作有问题 win10的系统
![image](https://user-images.githubusercontent.com/77323405/156118277-8e4d24f2-4cee-4444-8790-e87fe62658dd.png)

**Comment by SWHL** [comment]
- 项目的requirements.txt中忘记写这个库了
- 安装一下Pillow即可
```bash
pip install Pillow -i https://pypi.douban.com/simple/
```

**Comment by daliali2088** [comment]
> * 项目的要求.txt中忘记写这个库了
> * 安装一下枕即可
> 
> ```shell
> pip install Pillow -i https://pypi.douban.com/simple/
> ```

![image](https://user-images.githubusercontent.com/77323405/156119616-3b6da53a-5b7a-44f4-aab7-9f8bdc56b01b.png)

然后又显示这个了 文件也是从谷歌云下载的放进去了也
![image](https://user-images.githubusercontent.com/77323405/156119761-0d43e8a4-92a5-43b1-a5fc-27199e40b51b.png)

**Comment by SWHL** [comment]
添加QQ群：706807542
详细说一下吧
