### ISSUE TITLE
Preview and choosing region of interest

### ISSUE THREAD

**Issue by Johndirr** [SWHL/RapidVideOCR#16]
I like the the idea of detecting the subtitle size automatically but this is not working well at the moment. It is problematic to detect the right text if there are other texts like broadcasting logos or show titles and credits visible.
In the following case only the "Kiku" text was recognized as one long subtitle: 
![big_wing_01 avi_snapshot_00 54_ 2022 06 26_17 04 51](https://user-images.githubusercontent.com/15637513/175820663-81accc9d-f2f9-4f54-8e6a-0102132bd36a.png)
This is most likely because it was displayed first and never changed.

It would be nice if you make it possible to choose a region of interest. Every text that is not inside this region would be discarded or you cut out the ROI. I did something similar in the past:
```
def getROI(videopath):
    # init RegionOfInterest
    ROI = (0, 0, 0, 0)
    # create VideoCapture object
    cap = cv2.VideoCapture(videopath)
    # get the number of frames from the video for the endpoint of the trackbar
    numberofframes = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))

    # since cv2.createTrackbar requires a callbackfunction we use
    # a function that does nothing :)
    def onTrackbarChange(current_frame):
        pass

    # create a window called video and a trackbar called position
    cv2.namedWindow('video')
    cv2.createTrackbar( 'position', 'video', 0, numberofframes, onTrackbarChange)
    # displayOverlay is not working with the pip install of opencv
    # cv2.displayOverlay('video', "Press 'R-Button' to select region of interest", 5000)

    while True:
        # get videoposition from position in video
        videoposition = cv2.getTrackbarPos('position','video')
        #print("Videopos: " + str(videoposition))
        # goto videoposition and read frame
        cap.set(cv2.CAP_PROP_POS_FRAMES,videoposition)
        ret, frame = cap.read()
        # show frame in video if reading was successful
        if ret == True:
            cv2.imshow("video", frame)
        # keep the video open till a key gets pressed
        key = cv2.waitKey(1)

        # break when the s key gets pressed or get ROI when r gets pressed
        if key == ord("s"):
            break
        elif key == ord("r"):
            ROI = cv2.selectROI('video', frame, fromCenter=False, showCrosshair=False)
            # only end the loop if a ROI was choosen
            if ROI != (0, 0, 0, 0):
                break
    # release the video capture object and close all windows
    cap.release()
    cv2.destroyAllWindows()
    return ROI

ROI = getROI(args.video)
ret, frame = cap.read()
frame = frame[int(ROI[1]):int(ROI[1]+ROI[3]), int(ROI[0]):int(ROI[0]+ROI[2])]
```
Can you please implement a preview window where one can choose a frame of the video and pick a region of interest?
Maybe a "bad word" list, where you enter the broadcasting logo text, would also do.
If the results of the detection and recognition are depending on the size of the image it would also be nice to upscale frames that have a very low resolution.

I uploaded a sample video in case you need one:
https://drive.google.com/file/d/1rptaZGN0yzQ5ZEOuSB-HqGB-CpMqOFSY/view?usp=sharing

Thanks for your work!

**Comment by SWHL** [comment]
Thanks for your suggestion, I seriously consider it. Or you can submit a PR, welcome to discuss together.

**Comment by Johndirr** [comment]
I don't feel confident to submit a PR. :-) 

PS. I changed the permission of the linked video to "everyone". You should be able to have a look now.

**Comment by SWHL** [comment]
- Sorry to reply to you so late, your suggestion has been adopted and implemented, you can see the repository README for details.
- Thanks again.

**Comment by Johndirr** [comment]
Wow, nice to see you incorporating this into your project.
How do you feel about the results, do you think it's better to always crop the image or just discard any text that is not in the ROI?

**Comment by SWHL** [comment]
I think the way of always cropping the image is better.  If we have the all texts in the ROI, we can't select which one are useful.

**Comment by SWHL** [comment]
I will close this issue firstly, and you can open it again if necessary.
