### ISSUE TITLE
Output SRT file format is invalid.

### ISSUE THREAD

**Issue by 15kingben** [SWHL/RapidVideOCR#19]
Example result:

0:02:36,720 --> 0:02:37,879
请各单元组

0:02:37,880 --> 0:02:39,599
认真填写工作日志

1. Needs indexes
2. Hours require leading zeroes

Should be:
**1**
**0**0:02:36,720 --> **0**0:02:37,879
请各单元组

**2**
**0**0:02:37,880 --> **0**0:02:39,599
认真填写工作日志

**Comment by SWHL** [comment]
Mark, I will fix it later.

**Comment by SWHL** [comment]
I have fixed it

**Comment by SWHL** [comment]
I missed it. 
Now , I have fixed them all. 
Thansk for your reminder.

**Comment by 15kingben** [comment]
Thanks! It works for me now
