### ISSUE TITLE
`TXTImages`识别方式漏轴较多

### ISSUE THREAD

**Issue by dyphire** [SWHL/RapidVideOCR#21]
这是个非常好用的OCR字幕工具，但README.md里优先传入`TXTImages`进行识别的建议似乎不准确
经过测试`TXTImages`相比`RGBImages`的识别方式可以很好地保留字幕中的空格，但它漏轴的地方非常多
相比而言`RGBImages`识别方式基本不会漏轴

测试对比文本：
[RGBImages.txt](https://github.com/SWHL/RapidVideOCR/files/10905504/RGBImages.txt)
[TestImages.txt](https://github.com/SWHL/RapidVideOCR/files/10905505/TestImages.txt)

**Comment by SWHL** [comment]
感谢您的反馈，已经做了更改。
![image](https://user-images.githubusercontent.com/28639377/223331617-0cedd2fb-21f0-47c7-ae67-cb3934f769e8.png)


之前推荐TXTImages是我自己找了一个示例视频，没发现这个问题。

**Comment by dyphire** [comment]
还有个问题想问下，我看到更新日志里提到之前修复了同行字幕丢失空格的问题，但`RGBImages`识别中还是经常性地会丢失空格，这方面还有继续优化的可能性吗？
![image](https://user-images.githubusercontent.com/61936050/223615379-a32a6ffa-e880-47b3-be71-5a8275d749b5.png)

**Comment by SWHL** [comment]
有，这部分需要微调模型，不太容易修复，需要时间

**Comment by dyphire** [comment]
新版本的模型空格识别这块改善了很多，但文字准确率明显下降了
无论是否开启叠图识别模式都不如之前的版本，以牺牲文字准确度来还原空格的话感觉有些得不偿失
