### ISSUE TITLE
字幕超过一小时的部分时间轴出错

### ISSUE THREAD

**Issue by Sartalt** [SWHL/RapidVideOCR#23]
用VideoSubFinder生成的图片超过一小时的部分命名格式如图
![QQ截图20230327174120](https://user-images.githubusercontent.com/65516612/227905990-025a2cdd-2f7a-453d-b5b6-11dee3d05a25.png)
识图处理后生成的字幕时间轴变成了十小时
![QQ截图20230327175148](https://user-images.githubusercontent.com/65516612/227907496-81750ec4-8b14-4130-8b8d-3b8ed5417aff.png)

**Comment by SWHL** [comment]
问题已经在v2.1.6中修复
