### ISSUE TITLE
输入路径之后，点击ok程序闪退

### ISSUE THREAD

**Issue by mozeqiu123** [SWHL/RapidVideOCR#36]
填入两个路径，点击ok闪退了，我的图像路径里面是不是只能有图片，不能有其他的文件存在？而且我没看到有那个视频的解析呢
![image](https://github.com/SWHL/RapidVideOCR/assets/139750690/8d87f0bb-3115-4d55-9d5e-0eb527d68dc5)

**Comment by SWHL** [comment]
下载最新版本，试试 v0.0.4
https://github.com/SWHL/RapidVideOCR/releases/tag/v2.2.3
