### ISSUE TITLE
Google Colab

### ISSUE THREAD

**Issue by tvone** [SWHL/RapidVideOCR#45]
Not working in google colab, please update it
![image](https://github.com/SWHL/RapidVideOCR/assets/71977655/c6821ed4-1df3-4992-97cb-80584ab3f402)

**Comment by SWHL** [comment]
Had fixed it, please try again. [link](https://colab.research.google.com/github/SWHL/RapidVideOCR/blob/main/assets/RapidVideOCRDemo.ipynb)
