### ISSUE TITLE
rapid_videocr.main:110 - Extracting frames from tests/test_files/tiny/2.mp4 is 0, skip

### ISSUE THREAD

**Issue by yumianhuli1** [SWHL/RapidVideOCR#53]
使用项目中的demo.py
但是打印：| WARNING  | rapid_videocr.main:110 - Extracting frames from tests/test_files/tiny/2.mp4 is 0, skip
换了其他视频也是 0，skip

**Comment by SWHL** [comment]
`rapid_videocr`要和VideoSubFinder软件结合使用。
`rapid_videocr`的输入必须是VideoSubFinder的输出目录（RGBImages或者TXTImages）才可以。

**Comment by yumianhuli1** [comment]
> `rapid_videocr`要和VideoSubFinder软件结合使用。 `rapid_videocr`的输入必须是VideoSubFinder的输出目录（RGBImages或者TXTImages）才可以。

已解决，3Q
