### ISSUE TITLE
打包一个程序时，打开exe，报一个和rapid_videoc相关的错误

### ISSUE THREAD

**Issue by joseph16388** [SWHL/RapidVideOCR#59]
程序在打包前可运行，但打包后报一个和rapid_videoc相关的错误如下：
 File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "rapid_videocr\__init__.py", line 4, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "rapid_videocr\logger.py", line 34, in <module>
  File "rapid_videocr\logger.py", line 20, in get_logger
  File "loguru\_logger.py", line 865, in add
TypeError: Cannot log to objects of type 'NoneType'

**Comment by SWHL** [comment]
我未曾用pyinstaller打包过这个包，暂时也不知道哪里出了问题。你在查查吧

**Comment by joseph16388** [comment]
> 我未曾用pyinstaller打包过这个包，暂时也不知道哪里出了问题。你在查查吧

我用的auto-py-to-exe和另外一个工具，打包出来都是报这个错，然后今早我把rapid_videocr注释掉，就成功启动了EXE。

**Comment by SWHL** [comment]
能正常用了？

**Comment by joseph16388** [comment]
> 能正常用了？

注释掉rapid_videocr相关的依赖才可以正常用，不能打包只能换其他库，所以还是希望你能看一下打包的问题哈

**Comment by SWHL** [comment]
你那里0.0.9版本可以用不

---- 回复的原邮件 ----
| 发件人 | Mike ***@***.***> |
| 发送日期 | 2024年06月06日 12:12 |
| 收件人 | SWHL/RapidVideOCR ***@***.***> |
| 抄送人 | SWHL ***@***.***>,
Comment ***@***.***> |
| 主题 | Re: [SWHL/RapidVideOCR] 打包一个程序时，打开exe，报一个和rapid_videoc相关的错误 (Issue #59) |

能正常用了？

注释掉rapid_videocr相关的依赖才可以正常用，不能打包只能换其他库，所以还是希望你能看一下打包的问题哈

**Comment by joseph16388** [comment]
我目前用的RapidVideOCR版本信息是：
pip show rapid-videocr
Name: rapid-videocr
Version: 2.2.12
Summary: Tool for extracting hard subtitles from videos.
Home-page: https://github.com/SWHL/RapidVideOCR.git
Author: SWHL
Author-email: liekkaskono@163.com
License: Apache-2.0
Location: D:\AI\ChatGLM2\FanTui_Pack\venv\Lib\site-packages
Requires: loguru, rapidocr-onnxruntime, tqdm

0.0.9版本是哪个库的版本？

**Comment by joseph16388** [comment]
> 你那里0.0.9版本可以用不
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | Mike ***@***.***> | | 发送日期 | 2024年06月06日 12:12 | | 收件人 | SWHL/RapidVideOCR ***@***.***> | | 抄送人 | SWHL ***@***.***>, Comment ***@***.***> | | 主题 | Re: [SWHL/RapidVideOCR] 打包一个程序时，打开exe，报一个和rapid_videoc相关的错误 (Issue #59) | 能正常用了？ 注释掉rapid_videocr相关的依赖才可以正常用，不能打包只能换其他库，所以还是希望你能看一下打包的问题哈 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

我目前用的RapidVideOCR版本信息是：
pip show rapid-videocr
Name: rapid-videocr
Version: 2.2.12
Summary: Tool for extracting hard subtitles from videos.
Home-page: https://github.com/SWHL/RapidVideOCR.git
Author: SWHL
Author-email: [liekkaskono@163.com](mailto:liekkaskono@163.com)
License: Apache-2.0
Location: D:\AI\ChatGLM2\FanTui_Pack\venv\Lib\site-packages
Requires: loguru, rapidocr-onnxruntime, tqdm

0.0.9版本是哪个库的版本？

**Comment by SWHL** [comment]
我串台了，我以为你用的是[RapidVideOCRDesktop](https://github.com/SWHL/RapidVideOCRDesktop/releases/tag/v0.0.9)呢，误会误会

**Comment by joseph16388** [comment]
> 我串台了，我以为你用的是[RapidVideOCRDesktop](https://github.com/SWHL/RapidVideOCRDesktop/releases/tag/v0.0.9)呢，误会误会

嗯，rapid-videocr有时间的话看下打包报错的问题

**Comment by joseph16388** [comment]
> 我串台了，我以为你用的是[RapidVideOCRDesktop](https://github.com/SWHL/RapidVideOCRDesktop/releases/tag/v0.0.9)呢，误会误会

今天试了下可以打包了，但是运行时候报了一个和rapidocr_onnxruntime相关的错误：
 File "rapid_videocr\main.py", line 71, in __init__
  File "rapid_videocr\rapid_videocr.py", line 40, in __init__
  File "rapidocr_onnxruntime\main.py", line 39, in __init__
  File "rapidocr_onnxruntime\utils\parse_parameters.py", line 143, in __call__
  File "rapidocr_onnxruntime\utils\parse_parameters.py", line 153, in update_global_to_module
KeyError: 'intra_op_num_threads'
没打包之前，可以正常运行，@SWHL 可以根据报错想到点什么吗？

**Comment by SWHL** [comment]
安装最新的rapidocr_onnxruntime试试
