### ISSUE TITLE
RapidVideoSubFinderOCR这个类，但是这个类没有读取Det和Rec模型本地路径的接口

### ISSUE THREAD

**Issue by SWHL** [SWHL/RapidVideOCR#67]
你好！我目前用的是：
vsf_ocr = RapidVideoSubFinderOCR(
            vsf_exe_path=vsf_exe_path,
            is_concat_rec=True,
            create_cleared_text_images=False,
            open_video_opencv=open_video_opencv,
            open_video_ffmpeg=open_video_ffmpeg,
            use_cuda=True,
            top_video_image_percent_end=top_video_image_percent_end,
            bottom_video_image_percent_end=bottom_video_image_percent_end,
            left_video_image_percent_end=left_video_image_percent_end,
            right_video_image_percent_end=right_video_image_percent_end
        )
RapidVideoSubFinderOCR这个类，但是这个类没有读取Det和Rec模型本地路径的接口。。

_Originally posted by @joseph16388 in https://github.com/SWHL/RapidVideOCR/discussions/66#discussioncomment-10894857_

**Comment by SWHL** [comment]
已经在`rapidvideocr>=2.2.14`中支持

**Comment by joseph16388** [comment]
> 已经在`rapidvideocr>=2.2.14`中支持

你好！不过server版的OCR时间实在太长了，有没有提速或者使用其他OCR模型的方案呢？

**Comment by SWHL** [comment]
这个可以考虑用`rapidocr_paddle` GPU版提速了，如果有GPU的话。
相关教程：[rapidocr_paddle](https://rapidai.github.io/RapidOCRDocs/install_usage/rapidocr_paddle/usage/#_3)

需要先更改源码使用了

**Comment by joseph16388** [comment]
> 这个可以考虑用`rapidocr_paddle` GPU版提速了，如果有GPU的话。 相关教程：[rapidocr_paddle](https://rapidai.github.io/RapidOCRDocs/install_usage/rapidocr_paddle/usage/#_3)
> 
> 需要先更改源码使用了

好的，感谢！

**Comment by tvone** [comment]
Are you planning to update gpu support for this project?
